---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
{{ include "cert-manager.labels" . | indent 4 }}
  name: {{ include "cert-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
  - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.class }}
