---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cert-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]

- apiGroups: ["development.io"]
  resources: ["certificates", "certificates/status"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cert-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
