apiVersion: v1
data:
  {{- (.Files.Glob "files/gcp.json").AsSecrets | nindent 2 }}
kind: Secret
metadata:
  name: {{ include "cert-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
