---
apiVersion: v1
kind: Pod
metadata:
  name: examplecom
spec:
  containers:
  - name: mypod
    image: busybox
    command: ['sh', '-c', 'sleep 360000']
    volumeMounts:
    - name: certificate
      mountPath: "/certificate"
      readOnly: true
  volumes:
  - name: certificate
    secret:
      secretName: examplecom
